# Generated by Django 2.1 on 2019-07-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': 'BookCategory', 'verbose_name_plural': 'BookCategories'},
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(default='None', max_length=10),
            preserve_default=False,
        ),
    ]
