# Generated by Django 2.1 on 2019-07-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190714_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='bookcategory',
            name='nonce',
        ),
    ]
